# Build Stage
FROM maven:3.9.6-eclipse-temurin-21 as build
WORKDIR /app
COPY server/pom.xml .
COPY server/src ./src
RUN mvn clean package -DskipTests

# Run Stage
FROM eclipse-temurin:21-jre-alpine
WORKDIR /app
COPY --from=build /app/target/*.jar app.jar
EXPOSE 4050
ENTRYPOINT ["java", "-jar", "app.jar"]
